#APLICATION
spring.application.name=sistemawebraco
server.port=8090

# SWAGGER / SPRINGDOC
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true

#POSGRESS
spring.datasource.url=jdbc:postgresql://localhost:5432/secopp_raco_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#JWT
jwt.expiration=86400000
jwt.secret=${JWT_SECRET}

# OPENAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.chat.options.model=gpt-4o-mini

#SECOP
secop.api.base-url=https://www.datos.gov.co
secop.api.resource-path=/resource/p6dx-8zbt.json
secop.api.app-token=${SECOP_APP_TOKEN}

# TIMEOUTS
server.tomcat.connection-timeout=120000
spring.mvc.async.request-timeout=100000

# JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false



